 export const direccion = {
    latitud : 0,
    longitud : 0,
    direccion : "",
    ciudad : "",
    provincia : "",
    pais : "",
    codigoPostal : "",
    calle : "",
    numero : "",
    piso : "",
    departamento : "",
    entreCalles : "",
    referencia : "",
 }